--Create a new table to classify the teams into their respective continents
--This would allow the data to be presented in a map chart, making more meaningful insights.
CREATE TABLE TeamContinents (
    TeamName VARCHAR(100),
    Continent VARCHAR(100)
);

INSERT INTO TeamContinents (TeamName, Continent) 
VALUES 
    ('Italy', 'Europe'),
    ('France', 'Europe'),
    ('Switzerland', 'Europe'),
    ('Sweden', 'Europe'),
    ('England', 'Europe'),
    ('West Germany', 'Europe'),
    ('Germany', 'Europe'),
    ('Spain', 'Europe'),
    ('Russia', 'Europe'),
    ('Portugal', 'Europe'),
    ('Denmark', 'Europe'),
    ('Belgium', 'Europe'),
    ('Croatia', 'Europe'),
    ('Serbia', 'Europe'),
    ('Netherlands', 'Europe'),
    ('Poland', 'Europe'),
    ('Wales', 'Europe'),
    ('Austria', 'Europe'),
    ('Bosnia and Herzegovina', 'Europe'),
    ('Bulgaria', 'Europe'),
    ('Czech Republic', 'Europe'),
    ('Czechoslovakia', 'Europe'),
    ('East Germany', 'Europe'),
    ('FR Yugoslavia', 'Europe'),
    ('Greece', 'Europe'),
    ('Hungary', 'Europe'),
    ('Iceland', 'Europe'),
    ('Northern Ireland', 'Europe'),
    ('Norway', 'Europe'),
    ('Republic of Ireland', 'Europe'),
    ('Romania', 'Europe'),
    ('Scotland', 'Europe'),
    ('Serbia', 'Europe'),
    ('Serbia and Montenegro', 'Europe'),
    ('Slovakia', 'Europe'),
    ('Soviet Union', 'Europe'),
    ('Ukraine', 'Europe'),
    ('Yugoslavia', 'Europe'),
    ('Uruguay', 'South America'),
    ('Brazil', 'South America'),
    ('Chile', 'South America'),
    ('Argentina', 'South America'),
    ('Ecuador', 'South America'),
    ('Peru', 'South America'),
    ('Bolivia', 'South America'),
    ('Colombia', 'South America'),
    ('Paraguay', 'South America'),
    ('Trinidad and Tobago', 'South America'),
    ('Mexico', 'North America'),
    ('United States', 'North America'),
    ('Canada', 'North America'),
    ('Costa Rica', 'North America'),
    ('Cuba', 'North America'),
    ('El Salvador', 'North America'),
    ('Haiti', 'North America'),
    ('Honduras', 'North America'),
    ('Jamaica', 'North America'),
    ('Panama', 'North America'),
    ('USA', 'North America'),
    ('South Korea', 'Asia'),
    ('Japan', 'Asia'),
    ('China PR', 'Asia'),
    ('Dutch East Indies', 'Asia'),
    ('Iran', 'Asia'),
    ('Iraq', 'Asia'),
    ('Israel', 'Asia'),
    ('Kuwait', 'Asia'),
    ('North Korea', 'Asia'),
    ('Qatar', 'Asia'),
    ('Saudi Arabia', 'Asia'),
    ('Turkey', 'Asia'),
    ('United Arab Emirates', 'Asia'),
    ('Morocco', 'Africa'),
    ('South Africa', 'Africa'),
    ('Algeria', 'Africa'),
    ('Cameroon', 'Africa'),
    ('Egypt', 'Africa'),
    ('Ghana', 'Africa'),
    ('Ivory Coast', 'Africa'),
    ('Nigeria', 'Africa'),
    ('Senegal', 'Africa'),
    ('Togo', 'Africa'),
    ('Tunisia', 'Africa'),
    ('Zaire', 'Africa'),
    ('Australia', 'Oceania'),
    ('New Zealand', 'Oceania');


--Query the new Continent table
SELECT *
FROM dbo.TeamContinents
